import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            colors: {
                'on-tertiary': 'rgb(var(--c-on-tertiary) / <alpha-value>)',
                'surface-dim': 'rgb(var(--c-surface-dim) / <alpha-value>)',
                'tertiary-fixed-dim': 'rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)',
                'on-secondary-container': 'rgb(var(--c-on-secondary-container) / <alpha-value>)',
                'on-tertiary-fixed': 'rgb(var(--c-on-tertiary-fixed) / <alpha-value>)',
                'error-container': 'rgb(var(--c-error-container) / <alpha-value>)',
                'on-tertiary-container': 'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
                'on-background': 'rgb(var(--c-on-background) / <alpha-value>)',
                'tertiary-fixed': 'rgb(var(--c-tertiary-fixed) / <alpha-value>)',
                'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
                primary: 'rgb(var(--c-primary) / <alpha-value>)',
                outline: 'rgb(var(--c-outline) / <alpha-value>)',
                'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
                'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
                'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
                surface: 'rgb(var(--c-surface) / <alpha-value>)',
                'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
                background: 'rgb(var(--c-background) / <alpha-value>)',
                'secondary-fixed': 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
                'on-error': 'rgb(var(--c-on-error) / <alpha-value>)',
                'primary-fixed': 'rgb(var(--c-primary-fixed) / <alpha-value>)',
                'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
                'secondary-container': 'rgb(var(--c-secondary-container) / <alpha-value>)',
                tertiary: 'rgb(var(--c-tertiary) / <alpha-value>)',
                'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)',
                secondary: 'rgb(var(--c-secondary) / <alpha-value>)',
                'on-primary-fixed': 'rgb(var(--c-on-primary-fixed) / <alpha-value>)',
                'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
                'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
                'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
                'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
                'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
                'on-secondary-fixed': 'rgb(var(--c-on-secondary-fixed) / <alpha-value>)',
                'on-primary-fixed-variant': 'rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)',
                'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
                'on-primary-container': 'rgb(var(--c-on-primary-container) / <alpha-value>)',
                'tertiary-container': 'rgb(var(--c-tertiary-container) / <alpha-value>)',
                'surface-bright': 'rgb(var(--c-surface-bright) / <alpha-value>)',
                'primary-container': 'rgb(var(--c-primary-container) / <alpha-value>)',
                'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
                error: 'rgb(var(--c-error) / <alpha-value>)',
                'on-error-container': 'rgb(var(--c-on-error-container) / <alpha-value>)',
                'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
                'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
                'on-tertiary-fixed-variant': 'rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)',
                'on-secondary': 'rgb(var(--c-on-secondary) / <alpha-value>)',
                'surface-tint': 'rgb(var(--c-surface-tint) / <alpha-value>)',
                accent2: 'rgb(var(--c-accent2) / <alpha-value>)',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'space-2xs': '0.25rem',
                'space-xl': '2rem',
                'gutter-desktop': '2rem',
                'space-4xl': '6rem',
                'space-sm': '0.75rem',
                'space-xs': '0.5rem',
                'gutter-mobile': '1rem',
                'space-lg': '1.5rem',
                'space-md': '1rem',
                'space-3xl': '4.5rem',
                'space-2xl': '3rem',
                'max-width': '1280px',
            },
            fontFamily: {
                'label-sm': ['Space Grotesk', 'sans-serif'],
                'label-md': ['Space Grotesk', 'sans-serif'],
                'body-sm': ['Google Sans', 'sans-serif'],
                'headline-lg': ['Space Grotesk', 'sans-serif'],
                'body-lg': ['Google Sans', 'sans-serif'],
                'stat-counter': ['Space Grotesk', 'sans-serif'],
                'display-xl': ['Space Grotesk', 'sans-serif'],
                'display-xl-mobile': ['Space Grotesk', 'sans-serif'],
                'headline-md': ['Space Grotesk', 'sans-serif'],
                'body-md': ['Google Sans', 'sans-serif'],
                'headline-sm': ['Space Grotesk', 'sans-serif'],
                'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
                'display-md': ['Space Grotesk', 'sans-serif'],
                sans: ['Google Sans', 'sans-serif'],
            },
            fontSize: {
                'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
                'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
                'headline-lg': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'stat-counter': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '700' }],
                'display-xl-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
                'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '700' }],
                'display-md': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
            },
        },
    },

    plugins: [forms],
};
